// web/src/components/Navbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Search, Bell, User, LayoutGrid, Settings, Heart, Star, LogOut, ChevronDown } from 'lucide-vue-next'
import { useUserStore } from '@/store/user'
import { useRouter } from 'vue-router'

const userStore = useUserStore()
const router = useRouter()
const searchQuery = ref('')
const showDropdown = ref(false)

const toggleDropdown = () => {
  showDropdown.value = !showDropdown.value
}

const closeDropdown = (e: MouseEvent) => {
  const target = e.target as HTMLElement
  if (!target.closest('.user-dropdown-trigger')) {
    showDropdown.value = false
  }
}

const handleLogout = () => {
  userStore.logout()
  router.push('/auth/login')
  showDropdown.value = false
}

const handleSearch = () => {
  if (!searchQuery.value.trim()) return
  router.push({
    path: '/',
    query: { search: searchQuery.value.trim() }
  })
}

onMounted(() => {
  window.addEventListener('click', closeDropdown)
})

onUnmounted(() => {
  window.removeEventListener('click', closeDropdown)
})
</script>

<template>
  <nav class="sticky top-0 z-50 w-full border-b border-white/20 glass px-6 py-3 flex items-center justify-between">
    <div class="flex items-center gap-8">
      <!-- Logo -->
      <router-link to="/" class="flex items-center gap-2 group">
        <div class="w-10 h-10 bg-brand-primary rounded-xl flex items-center justify-center text-white shadow-lg shadow-blue-500/20 group-hover:scale-105 transition-transform">
          <LayoutGrid class="w-6 h-6" />
        </div>
        <span class="text-xl font-bold tracking-tight bg-gradient-to-r from-slate-900 to-slate-600 bg-clip-text text-transparent">
          CampusPulse
        </span>
      </router-link>
      
      <!-- Nav Links -->
      <div class="hidden lg:flex items-center gap-6">
        <router-link 
          to="/" 
          class="text-sm font-bold text-slate-600 hover:text-brand-primary transition-colors flex items-center gap-2"
          active-class="text-brand-primary"
        >
          <LayoutGrid class="w-4 h-4" /> 首页
        </router-link>
      </div>

      <!-- Search Bar -->
      <div class="hidden md:flex items-center relative w-96 group">
        <Search 
          @click="handleSearch"
          class="absolute left-3 w-4 h-4 text-slate-400 group-focus-within:text-brand-primary transition-colors cursor-pointer" 
        />
        <input 
          v-model="searchQuery"
          type="text" 
          placeholder="搜索热门话题、校园动态..."
          class="w-full bg-white/50 backdrop-blur-sm border border-slate-200/50 rounded-2xl py-2.5 pl-10 pr-4 text-sm focus:ring-2 focus:ring-brand-primary/20 focus:bg-white transition-all outline-none placeholder:text-slate-400 font-medium shadow-sm"
          @keyup.enter="handleSearch"
        />
      </div>
    </div>

    <!-- Actions -->
    <div class="flex items-center gap-4">
      <button class="p-2 hover:bg-slate-100 rounded-xl text-slate-500 transition-colors relative">
        <Bell class="w-5 h-5" />
        <span class="absolute top-2 right-2 w-2 h-2 bg-red-500 rounded-full border-2 border-white"></span>
      </button>

      <template v-if="userStore.isLoggedIn">
        <div class="relative user-dropdown-trigger">
          <button 
            @click="toggleDropdown"
            class="flex items-center gap-2 p-1 pl-1 pr-3 hover:bg-slate-100 rounded-full transition-colors border border-slate-200"
          >
            <div class="w-8 h-8 bg-slate-200 rounded-full flex items-center justify-center overflow-hidden border border-slate-200 shadow-sm">
              <img v-if="userStore.userInfo?.avatar" :src="userStore.userInfo.avatar" class="w-full h-full object-cover" />
              <User v-else class="w-5 h-5 text-slate-500" />
            </div>
            <span class="text-sm font-semibold text-slate-700">{{ userStore.userInfo?.nickname || '账户' }}</span>
            <ChevronDown class="w-4 h-4 text-slate-400 transition-transform" :class="{ 'rotate-180': showDropdown }" />
          </button>

          <!-- Dropdown -->
          <div 
            v-if="showDropdown"
            class="absolute right-0 mt-2 w-56 bg-white rounded-2xl shadow-xl shadow-slate-200/50 border border-slate-100 py-2 z-50 animate-in fade-in zoom-in duration-200"
          >
            <router-link 
                to="/profile" 
                @click="showDropdown = false"
                class="flex items-center gap-3 px-4 py-2.5 text-sm text-slate-600 hover:bg-slate-50 hover:text-brand-primary transition-colors"
            >
                <User class="w-4 h-4" /> 个人主页
            </router-link>
            <router-link 
                to="/my/likes" 
                @click="showDropdown = false"
                class="flex items-center gap-3 px-4 py-2.5 text-sm text-slate-600 hover:bg-slate-50 hover:text-brand-primary transition-colors"
            >
                <Heart class="w-4 h-4" /> 我的点赞
            </router-link>
            <router-link 
                to="/my/collections" 
                @click="showDropdown = false"
                class="flex items-center gap-3 px-4 py-2.5 text-sm text-slate-600 hover:bg-slate-50 hover:text-brand-primary transition-colors"
            >
                <Star class="w-4 h-4" /> 我的收藏
            </router-link>
            <router-link 
                to="/settings" 
                @click="showDropdown = false"
                class="flex items-center gap-3 px-4 py-2.5 text-sm text-slate-600 hover:bg-slate-50 hover:text-brand-primary transition-colors"
            >
                <Settings class="w-4 h-4" /> 系统设置
            </router-link>
            <div class="h-px bg-slate-100 my-1 mx-2"></div>
            <button 
                @click="handleLogout"
                class="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-red-500 hover:bg-red-50 transition-colors"
            >
                <LogOut class="w-4 h-4" /> 退出登录
            </button>
          </div>
        </div>
      </template>
      <template v-else>
        <router-link 
          to="/auth/login"
          class="px-5 py-2 bg-brand-primary text-white text-sm font-semibold rounded-xl hover:bg-blue-700 shadow-lg shadow-blue-500/20 transition-all active:scale-95"
        >
          立即登录
        </router-link>
      </template>
    </div>
  </nav>
</template>

// web/components/navbar.tsx
"use client"

import Link from "next/link"
import { useRouter } from "next/navigation"
import { usePathname } from "next/navigation"
import { Button } from "@/components/ui/button"
import {
    Bell,
    Search,
    LogOut,
    User,
    Settings,
    PenSquare,
    Menu,
    Plus
} from "lucide-react"
import { useState, useEffect } from "react"
import { motion, AnimatePresence } from "framer-motion"

export default function Navbar() {
    const router = useRouter()
    const pathname = usePathname()
    const [isScrolled, setIsScrolled] = useState(false)
    const [isLoggedIn, setIsLoggedIn] = useState(false)
    const [showUserMenu, setShowUserMenu] = useState(false)

    // 监听滚动以实现磨砂效果切换
    useEffect(() => {
        const handleScroll = () => {
            setIsScrolled(window.scrollY > 10)
        }
        window.addEventListener("scroll", handleScroll)
        // 检查登录状态
        setIsLoggedIn(!!localStorage.getItem("access_token"))
        return () => window.removeEventListener("scroll", handleScroll)
    }, [])

    const handleLogout = () => {
        localStorage.removeItem("access_token")
        localStorage.removeItem("refresh_token")
        setIsLoggedIn(false)
        router.push("/auth/login")
    }

    return (
        <header
            className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${isScrolled
                ? "bg-white/80 dark:bg-gray-900/80 backdrop-blur-md shadow-sm border-b border-gray-100 dark:border-gray-800"
                : "bg-transparent border-b border-transparent"
                }`}
        >
            <div className="container mx-auto px-4 h-16 flex items-center justify-between">
                {/* Logo */}
                <Link href="/" className="flex items-center space-x-2 group">
                    <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center transform transition-transform group-hover:rotate-12">
                        <span className="text-white font-bold text-xl">C</span>
                    </div>
                    <span className="font-bold text-xl tracking-tight text-gray-900 dark:text-white transition-colors">
                        Campus Pulse
                    </span>
                </Link>

                <nav className="hidden md:flex items-center space-x-1">
                    {[
                        { name: "首页", path: "/" },
                        { name: "趋势分析", path: "/trends" },
                        { name: "话题", path: "/topics" },
                    ].map((item) => (
                        <Link
                            key={item.path}
                            href={item.path}
                            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${pathname === item.path
                                ? "text-primary bg-primary/5"
                                : "text-gray-600 hover:text-primary hover:bg-gray-50"
                                }`}
                        >
                            {item.name}
                        </Link>
                    ))}
                </nav>

                {/* Right Actions */}
                <div className="flex items-center space-x-3">
                    {/* Search Trigger */}
                    <Button variant="ghost" size="icon" className="text-gray-500 hover:text-primary">
                        <Search className="w-5 h-5" />
                    </Button>

                    {isLoggedIn ? (
                        <>
                            <Button variant="ghost" size="icon" className="text-gray-500 hover:text-primary relative">
                                <Bell className="w-5 h-5" />
                                {/* Red dot for notification */}
                                <span className="absolute top-2 right-2 w-2 h-2 bg-red-500 rounded-full border border-white"></span>
                            </Button>

                            <Button
                                size="sm"
                                className="hidden md:flex rounded-full bg-primary hover:bg-primary/90 text-white shadow-sm shadow-primary/20 transition-all hover:scale-105 active:scale-95"
                                onClick={() => router.push('/post/create')}
                            >
                                <Plus className="w-4 h-4 mr-1.5" />
                                发帖
                            </Button>

                            {/* User Menu */}
                            <div className="relative">
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    className="rounded-full overflow-hidden border border-gray-200"
                                    onClick={() => setShowUserMenu(!showUserMenu)}
                                >
                                    <User className="w-5 h-5 text-gray-600" />
                                </Button>

                                <AnimatePresence>
                                    {showUserMenu && (
                                        <motion.div
                                            initial={{ opacity: 0, y: 10, scale: 0.95 }}
                                            animate={{ opacity: 1, y: 0, scale: 1 }}
                                            exit={{ opacity: 0, y: 10, scale: 0.95 }}
                                            transition={{ duration: 0.2 }}
                                            className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-xl border border-gray-100 py-1"
                                        >
                                            <Link href="/profile" className="flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">
                                                <User className="w-4 h-4 mr-2" /> 个人中心
                                            </Link>
                                            <Link href="/settings" className="flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">
                                                <Settings className="w-4 h-4 mr-2" /> 设置
                                            </Link>
                                            <div className="border-t my-1"></div>
                                            <button
                                                onClick={handleLogout}
                                                className="w-full flex items-center px-4 py-2 text-sm text-red-600 hover:bg-red-50"
                                            >
                                                <LogOut className="w-4 h-4 mr-2" /> 退出登录
                                            </button>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </div>
                        </>
                    ) : (
                        <div className="flex items-center space-x-2">
                            <Link href="/auth/login">
                                <Button variant="ghost" size="sm">登录</Button>
                            </Link>
                            <Link href="/auth/register">
                                <Button size="sm">注册</Button>
                            </Link>
                        </div>
                    )}
                </div>
            </div>
        </header>
    )
}
